-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: 14-Mar-2017 às 20:16
-- Versão do servidor: 10.1.21-MariaDB
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `moviny`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `movie`
--

CREATE TABLE `movie` (
  `mov_id` int(10) NOT NULL,
  `mov_id_imdb` varchar(13) DEFAULT NULL,
  `mov_url_imdb` varchar(70) DEFAULT NULL,
  `mov_title` varchar(300) DEFAULT NULL,
  `mov_original_title` varchar(300) DEFAULT NULL,
  `mov_url_poster` varchar(500) DEFAULT NULL,
  `mov_year` int(6) DEFAULT NULL,
  `mov_category` varchar(50) DEFAULT NULL,
  `mov_director` varchar(100) DEFAULT NULL,
  `mov_starring1` varchar(100) DEFAULT NULL,
  `mov_starring2` varchar(100) DEFAULT NULL,
  `mov_sinopsys` text,
  `mov_my_rating` decimal(3,1) DEFAULT NULL,
  `mov_imdb_rating` decimal(3,1) DEFAULT NULL,
  `mov_netflix` tinyint(1) DEFAULT NULL,
  `mov_watched` tinyint(1) DEFAULT NULL,
  `mov_registered` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Extraindo dados da tabela `movie`
--

INSERT INTO `movie` (`mov_id`, `mov_id_imdb`, `mov_url_imdb`, `mov_title`, `mov_original_title`, `mov_url_poster`, `mov_year`, `mov_category`, `mov_director`, `mov_starring1`, `mov_starring2`, `mov_sinopsys`, `mov_my_rating`, `mov_imdb_rating`, `mov_netflix`, `mov_watched`, `mov_registered`) VALUES
(54, 'tt0120689', 'http://www.imdb.com/title/tt0120689', 'À Espera de um Milagre', 'The Green Mile', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_UX182_CR0,0,182,268_AL_.jpg', 1999, 'Crime', 'Frank Darabont', 'Tom Hanks', 'David Morse', 'Death Row guards at a penitentiary, in the 1930\'s, have a moral dilemma with their job when they discover one of their prisoners, a convicted murderer, has a special gift.               ', '8.0', '8.5', 0, 0, '2017-03-12 14:34:13'),
(55, 'tt0099871', 'http://www.imdb.com/title/tt0099871', 'Alucinações do Passado', 'Jacob\'s Ladder', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjMwMDMxNzIzMF5BMl5BanBnXkFtZTgwMDMxNzQxMTE@._V1_UX182_CR0,0,182,268_AL_.jpg', 1990, 'Drama', 'Adrian Lyne', 'Tim Robbins', 'Elizabeth Peña', 'New York postal worker Jacob Singer is trying to keep his frayed life from unraveling. His days are increasingly being invaded by flashbacks to his first marriage, his now-dead son, and his tour of duty in Vietnam. Although his new wife tries to help Jacob keep his grip on sanity, the line between reality and delusion is steadily growing more and more uncertain.               ', '6.0', '7.5', 0, 1, '2017-03-12 14:39:27'),
(58, 'tt0137523', 'http://www.imdb.com/title/tt0137523', 'Clube da Luta', 'Fight Club', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZGY5Y2RjMmItNDg5Yy00NjUwLThjMTEtNDc2OGUzNTBiYmM1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg', 1999, 'Drama', 'David Fincher', 'Edward Norton', 'Brad Pitt', 'A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler\'s fight club, he must accept the awful truth that Tyler may not be who he says he is.               ', '8.0', '8.8', 0, 1, '2017-03-12 14:41:25'),
(59, 'tt0110912', 'http://www.imdb.com/title/tt0110912', 'Pulp Fiction: Tempo de Violência', 'Pulp Fiction', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_UX182_CR0,0,182,268_AL_.jpg', 1994, 'Crime', 'Quentin Tarantino', 'Tim Roth', 'Amanda Plummer', 'Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his weight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.               ', '9.5', '8.9', 1, 1, '2017-03-12 14:42:07'),
(60, 'tt0114369', 'http://www.imdb.com/title/tt0114369', 'Seven: Os Sete Crimes Capitais', 'Se7en', 'https://images-na.ssl-images-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg', 1995, 'Crime', 'David Fincher', 'Morgan Freeman', 'Andrew Kevin Walker', 'A film about two homicide detectives\' (Morgan Freeman and (Brad Pitt desperate hunt for a serial killer who justifies his crimes as absolution for the world\'s ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic \"John Doe\" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer\'s terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer\'s modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer...               ', '9.0', '8.6', 1, 1, '2017-03-12 14:42:36'),
(61, 'tt0109830', 'http://www.imdb.com/title/tt0109830', 'Forrest Gump: O Contador de Histórias', 'Forrest Gump', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYThjM2MwZGMtMzg3Ny00NGRkLWE4M2EtYTBiNWMzOTY0YTI4XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UY268_CR10,0,182,268_AL_.jpg', 1994, 'Comédia', 'Robert Zemeckis', 'Tom Hanks', 'Rebecca Williams', 'Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His \'mama\' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.               ', '8.5', '8.8', 1, 1, '2017-03-12 14:43:02'),
(62, 'tt0111161', 'http://www.imdb.com/title/tt0111161', 'Um Sonho de Liberdade', 'The Shawshank Redemption', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_UX182_CR0,0,182,268_AL_.jpg', 1994, 'Crime', 'Frank Darabont', 'Tim Robbins', 'Morgan Freeman', 'Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man\'s unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.               ', '8.0', '9.3', 1, 0, '2017-03-12 15:46:37'),
(69, 'tt0071562', 'http://www.imdb.com/title/tt0071562', 'O Poderoso Chefão II', 'The Godfather: Part II', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjZiNzIxNTQtNDc5Zi00YWY1LThkMTctMDgzYjY4YjI1YmQyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY268_CR3,0,182,268_AL_.jpg', 1974, 'Crime', 'Francis Ford Coppola', 'Al Pacino', 'Robert Duvall', 'The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.               ', '9.5', '9.0', 1, 0, '2017-03-12 16:06:39'),
(72, 'tt0099674', 'http://www.imdb.com/title/tt0099674', 'O Poderoso Chefão III', 'The Godfather: Part III', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTczMDcxNDA4MV5BMl5BanBnXkFtZTgwNjY1NTk4NjE@._V1_UX182_CR0,0,182,268_AL_.jpg', 1990, 'Crime', 'Francis Ford Coppola', 'Al Pacino', 'Diane Keaton', 'In the final instalment of the Godfather Trilogy, an aging Don Michael Corleone seeks to legitimize his crime family\'s interests and remove himself from the violent underworld but is kept back by the ambitions of the young. While he attempts to link the Corleone\'s finances with the Vatican, Michael must deal with the machinations of a hungrier gangster seeking to upset the existing Mafioso order and a young protoge\'s love affair with his daughter.               ', '8.0', '7.6', 1, 1, '2017-03-12 16:11:48'),
(73, 'tt0086250', 'http://www.imdb.com/title/tt0086250', 'Scarface', 'Scarface', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjAzOTM4MzEwNl5BMl5BanBnXkFtZTgwMzU1OTc1MDE@._V1_UX182_CR0,0,182,268_AL_.jpg', 1983, 'Crime', 'Brian De Palma', 'Al Pacino', 'Steven Bauer', 'Tony Montana manages to leave Cuba during the Mariel exodus of 1980. He finds himself in a Florida refugee camp but his friend Manny has a way out for them: undertake a contract killing and arrangements will be made to get a green card. He\'s soon working for drug dealer Frank Lopez and shows his mettle when a deal with Colombian drug dealers goes bad. He also brings a new level of violence to Miami. Tony is protective of his younger sister but his mother knows what he does for a living and disowns him. Tony is impatient and wants it all however, including Frank\'s empire and his mistress Elvira Hancock. Once at the top however, Tony\'s outrageous actions make him a target and everything comes crumbling down.               ', '9.0', '8.3', 1, 1, '2017-03-12 16:13:05'),
(74, 'tt0108052', 'http://www.imdb.com/title/tt0108052', 'A Lista de Schindler', 'Schindler\'s List', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg', 1993, 'Biography', 'Steven Spielberg', 'Liam Neeson', 'Ben Kingsley', 'Oskar Schindler is a vainglorious and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.               ', '7.0', '8.9', 1, 0, '2017-03-12 16:15:29'),
(75, 'tt2168180', 'http://www.imdb.com/title/tt2168180', 'Nise: O Coração da Loucura', 'Nise: O Coração da Loucura', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTcwNDY1NjU1OF5BMl5BanBnXkFtZTgwNTI0NTI4NzE@._V1_UX182_CR0,0,182,268_AL_.jpg', 2015, 'Biography', 'Roberto Berliner', 'Julio Adrião', 'Flavio Bauraqui', 'A miracle happened in Brazil on the 1950\'s. Renowned modern art museums opened their doors to artists nobody ever heard of. Many critics pointed out that theses exhibitions revealed painters that should be ranked amongst the best brazillian artists of the century. It was written that this explosion of art and beauty was a sign that something comparable to the renaissance was happening in Riio de Janeiro. Behind this miracle there was no art academy, patron or dealer, only a psychiatrist, ridiculed by her colleagues, and a painting studio at a mental hospital, in the outskirts of town. The artists were schizophrenic, poor, hospitalized for several decades, abandoned by their families and hopeless according to their doctors. This film tells the story of this \"Miracle\" and the life of this rebellious, frail and engaging psychiatrist: Dra. Nise da Silveira.               ', '0.0', '7.7', 0, 0, '2017-03-12 21:13:47'),
(76, 'tt2713180', 'http://www.imdb.com/title/tt2713180', 'Corações de Ferro', 'Fury', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4MDU0NTUyN15BMl5BanBnXkFtZTgwMzQxMzY4MjE@._V1_UX182_CR0,0,182,268_AL_.jpg', 2014, 'Ação', 'David Ayer', 'Brad Pitt', 'Shia LaBeouf', '1945, in World War II Germany, the tough Sergeant Don \'Wardaddy\' Collier commands a tank and survives a German attack with his veteran crew composed of Boyd \'Bible\' Swan, Trini \'Gordo\' Garcia and Grady \'Coon-Ass\' Travis. He receives a rookie soldier Norman Ellison as the substitute for his deceased gunner and he tries to harden the youth along the way.               ', '0.0', '7.6', 0, 0, '2017-03-12 21:14:48'),
(77, 'tt2015381', 'http://www.imdb.com/title/tt2015381', 'Guardiões da Galáxia', 'Guardians of the Galaxy', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_UX182_CR0,0,182,268_AL_.jpg', 2014, 'Ação', 'James Gunn', 'Chris Pratt', 'Zoe Saldana', 'After stealing a mysterious orb in the far reaches of outer space, Peter Quill from Earth, is now the main target of a manhunt led by the villain known as Ronan the Accuser. To help fight Ronan and his team and save the galaxy from his power, Quill creates a team of space heroes known as the \"Guardians of the Galaxy\" to save the world.               ', '9.0', '8.1', 0, 1, '2017-03-13 08:16:45'),
(80, 'tt2395427', 'http://www.imdb.com/title/tt2395427', 'Vingadores: Era de Ultron', 'Avengers: Age of Ultron', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_UX182_CR0,0,182,268_AL_.jpg', 2015, 'Ação', 'Joss Whedon', 'Robert Downey Jr.', 'Chris Hemsworth', 'Tony Stark creates the Ultron Program to protect the world, but when the peacekeeping program becomes hostile, The Avengers go into action to try and defeat a virtually impossible enemy together. Earth\'s mightiest heroes must come together once again to protect the world from global extinction.               ', '9.0', '7.4', 0, 1, '2017-03-13 08:59:49'),
(81, 'tt1843866', 'http://www.imdb.com/title/tt1843866', 'Capitão América 2: O Soldado Invernal', 'Captain America: The Winter Soldier', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_UY268_CR1,0,182,268_AL_.jpg', 2014, 'Ação', 'Anthony Russo', 'Chris Evans', 'Samuel L. Jackson', 'For Steve Rogers, awakening after decades of suspended animation involves more than catching up on pop culture; it also means that this old school idealist must face a world of subtler threats and difficult moral complexities. That becomes clear when Director Nick Fury is killed by the mysterious assassin, the Winter Soldier, but not before warning Rogers that SHIELD has been subverted by its enemies. When Rogers acts on Fury\'s warning to trust no one there, he is branded as a traitor by the organization. Now a fugitive, Captain America must get to the bottom of this deadly mystery with the help of the Black Widow and his new friend, The Falcon. However, the battle will be costly for the Sentinel of Liberty, with Rogers finding enemies where he least expects them while learning that the Winter Soldier looks disturbingly familiar.               ', '8.0', '7.8', 0, 1, '2017-03-13 09:04:38'),
(82, 'tt1300854', 'http://www.imdb.com/title/tt1300854', 'Homem de Ferro 3', 'Iron Man Three', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzMjEzMjY1M15BMl5BanBnXkFtZTcwNTMxOTYyOQ@@._V1_UY268_CR3,0,182,268_AL_.jpg', 2013, 'Ação', 'Shane Black', 'Robert Downey Jr.', 'Gwyneth Paltrow', 'Marvel\'s \"Iron Man 3\" pits brash-but-brilliant industrialist Tony Stark/Iron Man against an enemy whose reach knows no bounds. When Stark finds his personal world destroyed at his enemy\'s hands, he embarks on a harrowing quest to find those responsible. This journey, at every turn, will test his mettle. With his back against the wall, Stark is left to survive by his own devices, relying on his ingenuity and instincts to protect those closest to him. As he fights his way back, Stark discovers the answer to the question that has secretly haunted him: does the man make the suit or does the suit make the man?               ', '8.0', '7.2', 0, 1, '2017-03-13 09:06:17'),
(83, 'tt0848228', 'http://www.imdb.com/title/tt0848228', 'The Avengers: Os Vingadores', 'The Avengers', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2012, 'Ação', 'Joss Whedon', 'Robert Downey Jr.', 'Chris Evans', 'Nick Fury is the director of S.H.I.E.L.D., an international peace-keeping agency. The agency is a who\'s who of Marvel Super Heroes, with Iron Man, The Incredible Hulk, Thor, Captain America, Hawkeye and Black Widow. When global security is threatened by Loki and his cohorts, Nick Fury and his team will need all their powers to save the world from disaster.               ', '8.0', '8.1', 0, 1, '2017-03-13 10:07:42'),
(84, 'tt0371746', 'http://www.imdb.com/title/tt0371746', 'Homem de Ferro', 'Iron Man', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2008, 'Ação', 'Jon Favreau', 'Robert Downey Jr.', 'Terrence Howard', 'Tony Stark. Genius, billionaire, playboy, philanthropist. Son of legendary inventor and weapons contractor Howard Stark. When Tony Stark is assigned to give a weapons presentation to an Iraqi unit led by Lt. Col. James Rhodes, he\'s given a ride on enemy lines. That ride ends badly when Stark\'s Humvee that he\'s riding in is attacked by enemy combatants. He survives - barely - with a chest full of shrapnel and a car battery attached to his heart. In order to survive he comes up with a way to miniaturize the battery and figures out that the battery can power something else. Thus Iron Man is born. He uses the primitive device to escape from the cave in Iraq. Once back home, he then begins work on perfecting the Iron Man suit. But the man who was put in charge of Stark Industries has plans of his own to take over Tony\'s technology for other matters.               ', '8.0', '7.9', 0, 1, '2017-03-13 11:10:06'),
(85, 'tt0948470', 'http://www.imdb.com/title/tt0948470', 'O Espetacular Homem-Aranha', 'The Amazing Spider-Man', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjMyOTM4MDMxNV5BMl5BanBnXkFtZTcwNjIyNzExOA@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2012, 'Ação', 'Marc Webb', 'Andrew Garfield', 'Emma Stone', 'Peter Parker (Garfield) is an outcast high schooler who was abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben (Sheen) and Aunt May (Field). Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. Peter is also finding his way with his first high school crush, Gwen Stacy (Stone), and together, they struggle with love, commitment, and secrets. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents\' disappearance - leading him directly to Oscorp and the lab of Dr. Curt Connors (Ifans), his father\'s former partner. As Spider-Man is set on a collision course with Connors\' alter-ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.               ', '0.0', '7.0', 0, 0, '2017-03-13 12:58:37'),
(86, 'tt1872181', 'http://www.imdb.com/title/tt1872181', 'O Espetacular Homem-Aranha 2: A Ameaça de Electro', 'The Amazing Spider-Man 2', 'https://images-na.ssl-images-amazon.com/images/M/MV5BOTA5NDYxNTg0OV5BMl5BanBnXkFtZTgwODE5NzU1MTE@._V1_UX182_CR0,0,182,268_AL_.jpg', 2014, 'Ação', 'Marc Webb', 'Andrew Garfield', 'Emma Stone', 'We\'ve always known that Spider-Man\'s most important conflict has been within himself: the struggle between the ordinary obligations of Peter Parker and the extraordinary responsibilities of Spider-Man. But in The Amazing Spider-Man 2, Peter Parker finds that his greatest battle is about to begin. It\'s great to be Spider-Man. For Peter Parker, there\'s no feeling quite like swinging between skyscrapers, embracing being the hero, and spending time with Gwen. But being Spider-Man comes at a price: only Spider-Man can protect his fellow New Yorkers from the formidable villains that threaten the city. With the emergence of Electro, Peter must confront a foe far more powerful than he. And as his old friend, Harry Osborn, returns, Peter comes to realize that all of his enemies have one thing in common: Oscorp.               ', '0.0', '6.7', 1, 0, '2017-03-13 13:03:37'),
(87, 'tt0413300', 'http://www.imdb.com/title/tt0413300', 'Homem-Aranha 3', 'Spider-Man 3', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYTk3MDljOWQtNGI2My00OTEzLTlhYjQtOTQ4ODM2MzUwY2IwXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX182_CR0,0,182,268_AL_.jpg', 2007, 'Ação', 'Sam Raimi', 'Tobey Maguire', 'Kirsten Dunst', 'Peter Parker has finally managed to piece together the once-broken parts of his life, maintaining a balance between his relationship with Mary-Jane and his responsibility as Spider-Man. But more challenges arise for our young hero. Peter\'s old friend Harry Obsourne has set out for revenge against Peter; taking up the mantle of his late father\'s persona as The New Goblin, and Peter must also capture Uncle Ben\'s real killer, Flint Marko, who has been transformed into his toughest foe yet, the Sandman. All hope seems lost when suddenly Peter\'s suit turns jet-black and greatly amplifies his powers. But it also begins to greatly amplify the much darker qualities of Peter\'s personality that he begins to lose himself to. Peter has to reach deep inside himself to free the compassionate hero he used to be if he is to ever conquer the darkness within and face not only his greatest enemies, but also...himself.               ', '0.0', '6.2', 1, 0, '2017-03-13 13:06:20'),
(88, 'tt0120789', 'http://www.imdb.com/title/tt0120789', 'A Vida em Preto E Branco', 'Pleasantville', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYTRlYzk4NDktODE3Ni00YjFkLWFjYmUtNjg1MzdmYmFmOTJkXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_UX182_CR0,0,182,268_AL_.jpg', 1998, 'Comédia', 'Gary Ross', 'Tobey Maguire', 'Reese Witherspoon', 'David, nerdy high school student, flees reality by watching Pleasantville - a 1950\'s b&w sit-com, where everything is just that... pleasant. His sister Jennifer, sexually far more active than her brother, gets in a fight with him about a very strange remote control. The remote was given to them just seconds after the TV broke, by an equally strange repair man. They suddenly find themselves in Pleasantville, as Bud and Mary-Sue Parker, completely assimilated and therefore black and white, in clothes a little different and with new parents... pleasant ones. David wants to get out of the situation as well as his sister, but whereas he tries to blend in (effortlessly, with his knowledge), she does whatever she wants to do. One event leads to the other, and suddenly there is a red rose growing in Pleasantville. The more rules are broken, the more colorful life gets in Pleasantville, USA.               ', '0.0', '7.5', 1, 0, '2017-03-13 13:08:08'),
(89, 'tt1285016', 'http://www.imdb.com/title/tt1285016', 'A Rede Social', 'The Social Network', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTM2ODk0NDAwMF5BMl5BanBnXkFtZTcwNTM1MDc2Mw@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2010, 'Biography', 'David Fincher', 'Jesse Eisenberg', 'Rooney Mara', 'On a fall night in 2003, Harvard undergrad and computer programming genius Mark Zuckerberg sits down at his computer and heatedly begins working on a new idea. In a fury of blogging and programming, what begins in his dorm room soon becomes a global social network and a revolution in communication. A mere six years and 500 million friends later, Mark Zuckerberg is the youngest billionaire in history... but for this entrepreneur, success leads to both personal and legal complications.               ', '0.0', '7.7', 0, 0, '2017-03-13 13:11:00'),
(90, 'tt0947798', 'http://www.imdb.com/title/tt0947798', 'Cisne Negro', 'Black Swan', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2010, 'Drama', 'Darren Aronofsky', 'Natalie Portman', 'Mila Kunis', 'Nina (Portman) is a ballerina in a New York City ballet company whose life, like all those in her profession, is completely consumed with dance. She lives with her obsessive former ballerina mother Erica (Hershey) who exerts a suffocating control over her. When artistic director Thomas Leroy (Cassel) decides to replace prima ballerina Beth MacIntyre (Ryder) for the opening production of their new season, Swan Lake, Nina is his first choice. But Nina has competition: a new dancer, Lily (Kunis), who impresses Leroy as well. Swan Lake requires a dancer who can play both the White Swan with innocence and grace, and the Black Swan, who represents guile and sensuality. Nina fits the White Swan role perfectly but Lily is the personification of the Black Swan. As the two young dancers expand their rivalry into a twisted friendship, Nina begins to get more in touch with her dark side - a recklessness that threatens to destroy her.               ', '8.6', '8.0', 1, 1, '2017-03-13 13:16:23'),
(91, 'tt1454468', 'http://www.imdb.com/title/tt1454468', 'Gravidade', 'Gravity', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2013, 'Aventura', 'Alfonso Cuarón', 'Sandra Bullock', 'George Clooney', 'Dr. Ryan Stone (Sandra Bullock) is a brilliant medical engineer on her first shuttle mission, with veteran astronaut Matt Kowalski (George Clooney) in command of his last flight before retiring. But on a seemingly routine spacewalk, disaster strikes. The shuttle is destroyed, leaving Stone and Kowalsky completely alone - tethered to nothing but each other and spiraling out into the blackness.               ', '8.6', '7.8', 0, 0, '2017-03-13 13:17:29'),
(92, 'tt3659388', 'http://www.imdb.com/title/tt3659388', 'Perdido em Marte', 'The Martian', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_UX182_CR0,0,182,268_AL_.jpg', 2015, 'Aventura', 'Ridley Scott', 'Matt Damon', 'Jessica Chastain', 'During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive. Millions of miles away, NASA and a team of international scientists work tirelessly to bring \"the Martian\" home, while his crewmates concurrently plot a daring, if not impossible, rescue mission. As these stories of incredible bravery unfold, the world comes together to root for Watney\'s safe return.               ', '11.0', '8.0', 0, 0, '2017-03-13 13:19:36'),
(93, 'tt1663202', 'http://www.imdb.com/title/tt1663202', 'O Regresso', 'The Revenant', 'https://images-na.ssl-images-amazon.com/images/M/MV5BY2FmODc2N2QtYmY3MS00YTMwLWI2NGYtZWRmYWVkNjFjZmI0XkEyXkFqcGdeQXVyNTMxMjgxMzA@._V1_UX182_CR0,0,182,268_AL_.jpg', 2015, 'Aventura', 'Alejandro G. Iñárritu', 'Leonardo DiCaprio', 'Tom Hardy', 'While exploring the uncharted wilderness in 1823, legendary frontiersman Hugh Glass sustains injuries from a brutal bear attack. When his hunting team leaves him for dead, Glass must utilize his survival skills to find a way back home while avoiding natives on their own hunt. Grief-stricken and fueled by vengeance, Glass treks through the wintry terrain to track down John Fitzgerald, the former confidant who betrayed and abandoned him.               ', '0.0', '8.0', 1, 0, '2017-03-13 14:26:12'),
(94, 'tt1392190', 'http://www.imdb.com/title/tt1392190', 'Mad Max: Estrada da Fúria', 'Mad Max: Fury Road', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyMTE0ODcxNF5BMl5BanBnXkFtZTgwODE4NDQzNTE@._V1_UY268_CR1,0,182,268_AL_.jpg', 2015, 'Ação', 'George Miller', 'Tom Hardy', 'Charlize Theron', 'An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and almost everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order. There\'s Max, a man of action and a man of few words, who seeks peace of mind following the loss of his wife and child in the aftermath of the chaos. And Furiosa, a woman of action and a woman who believes her path to survival may be achieved if she can make it across the desert back to her childhood homeland.               ', '0.0', '8.1', 1, 0, '2017-03-13 14:29:30'),
(95, 'tt0993846', 'http://www.imdb.com/title/tt0993846', 'O Lobo de Wall Street', 'The Wolf of Wall Street', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_UX182_CR0,0,182,268_AL_.jpg', 2013, 'Biography', 'Martin Scorsese', 'Leonardo DiCaprio', 'Jonah Hill', 'Jordan Belfort is a Long Island penny stockbroker who served 22 months in prison for defrauding investors in a massive 1990s securities scam that involved widespread corruption on Wall Street and in the corporate banking world, including shoe designer Steve Madden.               ', '0.0', '8.2', 1, 0, '2017-03-13 14:30:41'),
(96, 'tt0361748', 'http://www.imdb.com/title/tt0361748', 'Bastardos Inglórios', 'Inglourious Basterds', 'https://images-na.ssl-images-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX182_CR0,0,182,268_AL_.jpg', 2009, 'Aventura', 'Quentin Tarantino', 'Brad Pitt', 'Mélanie Laurent', 'In German-occupied France, young Jewish refugee Shosanna Dreyfus witnesses the slaughter of her family by Colonel Hans Landa. Narrowly escaping with her life, she plots her revenge several years later when German war hero Fredrick Zoller takes a rapid interest in her and arranges an illustrious movie premiere at the theater she now runs. With the promise of every major Nazi officer in attendance, the event catches the attention of the \"Basterds\", a group of Jewish-American guerrilla soldiers led by the ruthless Lt. Aldo Raine. As the relentless executioners advance and the conspiring young girl\'s plans are set in motion, their paths will cross for a fateful evening that will shake the very annals of history.               ', '0.0', '8.3', 1, 0, '2017-03-13 14:33:26'),
(97, 'tt0105236', 'http://www.imdb.com/title/tt0105236', 'Cães de Aluguel', 'Reservoir Dogs', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNDc0YWFhMmQtOTFhZC00MzViLTlkNjctMWUzYTI2YWFkNzVlXkEyXkFqcGdeQXVyNjE5MjUyOTM@._V1_UX182_CR0,0,182,268_AL_.jpg', 1992, 'Crime', 'Quentin Tarantino', 'Harvey Keitel', 'Tim Roth', 'Six criminals, who are strangers to each other, are hired by a crime boss, Joe Cabot, to carry out a diamond robbery. Right at the outset, they are given false names with the intention that they won\'t get too close and will concentrate on the job instead. They are completely sure that the robbery is going to be a success. But, when the police show up right at the time and the site of the robbery, panic spreads amongst the group members, and two of them are killed in the subsequent shootout, along with a few policemen and civilians. When the remaining people assemble at the premeditated rendezvous point (a warehouse), they begin to suspect that one of them is an undercover cop.               ', '0.0', '8.4', 1, 0, '2017-03-13 14:36:51'),
(98, 'tt0120586', 'http://www.imdb.com/title/tt0120586', 'A Outra História Americana', 'American History X', 'https://images-na.ssl-images-amazon.com/images/M/MV5BY2E2MWU5ZDktOTQ0OS00NGIzLTg4YTgtYjFhNTRlMjA1NzFjL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UY268_CR0,0,182,268_AL_.jpg', 1998, 'Crime', 'Tony Kaye', 'Edward Norton', 'Edward Furlong', 'Derek Vineyard is paroled after serving 3 years in prison for brutally killing two black men who tried to break into/steal his truck. Through his brother, Danny Vineyard\'s narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.               ', '7.5', '8.6', 0, 0, '2017-03-13 14:40:58'),
(99, 'tt0120815', 'http://www.imdb.com/title/tt0120815', 'O Resgate do Soldado Ryan', 'Saving Private Ryan', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UY268_CR0,0,182,268_AL_.jpg', 1998, 'Drama', 'Steven Spielberg', 'Tom Hanks', 'Tom Sizemore', 'Opening with the Allied invasion of Normandy on 6 June 1944, members of the 2nd Ranger Battalion under Cpt. Miller fight ashore to secure a beachhead. Amidst the fighting, two brothers are killed in action. Earlier in New Guinea, a third brother is KIA. Their mother, Mrs. Ryan, is to receive all three of the grave telegrams on the same day. The United States Army Chief of Staff, George C. Marshall, is given an opportunity to alleviate some of her grief when he learns of a fourth brother, Private James Ryan, and decides to send out 8 men (Cpt. Miller and select members from 2nd Rangers) to find him and bring him back home to his mother...               ', '0.0', '8.6', 0, 0, '2017-03-13 15:14:28'),
(100, 'tt0112573', 'http://www.imdb.com/title/tt0112573', 'Coração Valente', 'Braveheart', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNTMyNGE1ODQtYTNiNS00ZTUyLThhZjktMTgyOGZkZThlYTc3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg', 1995, 'Biography', 'Mel Gibson', 'James Robinson', 'Sean Lawlor', 'William Wallace is a Scottish rebel who leads an uprising against the cruel English ruler Edward the Longshanks, who wishes to inherit the crown of Scotland for himself. When he was a young boy, William Wallace\'s father and brother, along with many others, lost their lives trying to free Scotland. Once he loses another of his loved ones, William Wallace begins his long quest to make Scotland free once and for all, along with the assistance of Robert the Bruce.               ', '0.0', '8.4', 0, 0, '2017-03-13 15:18:11'),
(101, 'tt0167261', 'http://www.imdb.com/title/tt0167261', 'O Senhor dos Anéis: As Duas Torres', 'The Lord of the Rings: The Two Towers', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTAyNDU0NjY4NTheQTJeQWpwZ15BbWU2MDk4MTY2Nw@@._V1_UY268_CR0,0,182,268_AL_.jpg', 2002, 'Aventura', 'Peter Jackson', 'Bruce Allpress', 'Sean Astin', ' While Frodo and Sam, now accompanied by a new guide, continue their hopeless journey towards the land of shadow to destroy the One Ring, each member of the broken fellowship plays their part in the battle against the evil wizard Saruman and his armies of Isengard.            ', '0.0', '8.7', 0, 0, '2017-03-13 15:19:41'),
(102, 'tt0080684', 'http://www.imdb.com/title/tt0080684', 'O Império Contra-Ataca', 'Star Wars: Episode V - The Empire Strikes Back', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYmViY2M2MTYtY2MzOS00YjQ1LWIzYmEtOTBiNjhlMGM0NjZjXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX182_CR0,0,182,268_AL_.jpg', 1980, 'Ação', 'Irvin Kershner', 'Mark Hamill', 'Harrison Ford', 'Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi master\'s help will Luke survive when the dark side of the Force beckons him into the ultimate duel with Darth Vader.               ', '0.0', '8.8', 0, 0, '2017-03-13 15:24:52'),
(103, 'tt0086190', 'http://www.imdb.com/title/tt0086190', 'O Retorno de Jedi', 'Star Wars: Episode VI - Return of the Jedi', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODllZjg2YjUtNWEzNy00ZGY2LTgyZmQtYTkxNDYyOWM3OTUyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg', 1983, 'Ação', 'Richard Marquand', 'Mark Hamill', 'Harrison Ford', 'Luke Skywalker battles horrible Jabba the Hut and cruel Darth Vader to save his comrades in the Rebel Alliance and triumph over the Galactic Empire. Han Solo and Princess Leia reaffirm their love and team with Chewbacca, Lando Calrissian, the Ewoks and the androids C-3PO and R2-D2 to aid in the disruption of the Dark Side and the defeat of the evil emperor.               ', '0.0', '8.4', 0, 0, '2017-03-13 15:32:36'),
(104, 'tt0120915', 'http://www.imdb.com/title/tt0120915', 'Star Wars: Episódio I - A Ameaça Fantasma', 'Star Wars: Episode I - The Phantom Menace', 'https://images-na.ssl-images-amazon.com/images/M/MV5BM2FmZGIwMzAtZTBkMS00M2JiLTk2MDctM2FlNTQ2OWYwZDZkXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX182_CR0,0,182,268_AL_.jpg', 1999, 'Ação', 'George Lucas', 'Liam Neeson', 'Ewan McGregor', 'The evil Trade Federation, led by Nute Gunray is planning to take over the peaceful world of Naboo. Jedi Knights Qui-Gon Jinn and Obi-Wan Kenobi are sent to confront the leaders. But not everything goes to plan. The two Jedi escape, and along with their new Gungan friend, Jar Jar Binks head to Naboo to warn Queen Amidala, but droids have already started to capture Naboo and the Queen is not safe there. Eventually, they land on Tatooine, where they become friends with a young boy known as Anakin Skywalker. Qui-Gon is curious about the boy, and sees a bright future for him. The group must now find a way of getting to Coruscant and to finally solve this trade dispute, but there is someone else hiding in the shadows. Are the Sith really extinct? Is the Queen really who she says she is? And what\'s so special about this young boy?               ', '0.0', '6.5', 1, 1, '2017-03-13 15:34:13'),
(105, 'tt0121765', 'http://www.imdb.com/title/tt0121765', 'Star Wars: Episódio II - Ataque dos Clones', 'Star Wars: Episode II - Attack of the Clones', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNDRkYzA4OGYtOTBjYy00YzFiLThhYmYtMWUzMDBmMmZkM2M3XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UY268_CR10,0,182,268_AL_.jpg', 2002, 'Ação', 'George Lucas', 'Ewan McGregor', 'Natalie Portman', 'Ten years after the invasion of Naboo, the Galactic Republic is facing a Separatist movement and the former queen and now Senator Padmé Amidala travels to Coruscant to vote on a project to create an army to help the Jedi to protect the Republic. Upon arrival, she escapes from an attempt to kill her, and Obi-Wan Kenobi and his Padawan Anakin Skywalker are assigned to protect her. They chase the shape-shifter Zam Wessell but she is killed by a poisoned dart before revealing who hired her. The Jedi Council assigns Obi-Wan Kenobi to discover who has tried to kill Amidala and Anakin to protect her in Naboo. Obi-Wan discovers that the dart is from the planet Kamino, and he heads to the remote planet. He finds an army of clones that has been under production for years for the Republic and that the bounty hunter Jango Fett was the matrix for the clones. Meanwhile Anakin and Amidala fall in love with each other, and he has nightmarish visions of his mother. They travel to his home planet, ...               ', '0.0', '6.7', 0, 1, '2017-03-13 15:37:11'),
(106, 'tt0121766', 'http://www.imdb.com/title/tt0121766', 'Star Wars: Episódio III - A Vingança dos Sith', 'Star Wars: Episode III - Revenge of the Sith', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_UY268_CR9,0,182,268_AL_.jpg', 2005, 'Ação', 'George Lucas', 'Ewan McGregor', 'Natalie Portman', ' Near the end of the Clone Wars, Darth Sidious has revealed himself and is ready to execute the last part of his plan to rule the galaxy. Sidious is ready for his new apprentice, Darth Vader, to step into action and kill the remaining Jedi. Vader, however, struggles to choose the dark side and save his wife or remain loyal to the Jedi order.            ', '0.0', '7.6', 0, 1, '2017-03-13 15:38:59'),
(107, 'tt0209144', 'http://www.imdb.com/title/tt0209144', 'Amnésia', 'Memento', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY268_CR0,0,182,268_AL_.jpg', 2000, 'Mistério', 'Christopher Nolan', 'Guy Pearce', 'Carrie-Anne Moss', 'Memento chronicles two separate stories of Leonard, an ex-insurance investigator who can no longer build new memories, as he attempts to find the murderer of his wife, which is the last thing he remembers. One story line moves forward in time while the other tells the story backwards revealing more each time.               ', '0.0', '8.5', 0, 1, '2017-03-13 15:42:19'),
(108, 'tt0816692', 'http://www.imdb.com/title/tt0816692', 'Interestelar', 'Interstellar', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_UX182_CR0,0,182,268_AL_.jpg', 2014, 'Aventura', 'Christopher Nolan', 'Ellen Burstyn', 'Matthew McConaughey', ' Earth\'s future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind\'s survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.            ', '5.0', '8.6', 0, 1, '2017-03-13 15:45:51'),
(109, 'tt3315342', 'http://www.imdb.com/title/tt3315342', 'Logan', 'Logan', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1MjkzMjczMV5BMl5BanBnXkFtZTgwNDk4NjYyMTI@._V1_UX182_CR0,0,182,268_AL_.jpg', 2017, 'Ação', 'James Mangold', 'Hugh Jackman', 'Patrick Stewart', ' In 2029 the mutant population has shrunk significantly and the X-Men have disbanded. Logan, whose power to self-heal is dwindling, has surrendered himself to alcohol and now earns a living as a chauffeur. He takes care of the ailing old Professor X whom he keeps hidden away. One day, a female stranger asks Logan to drive a girl named Laura to the Canadian border. At first he refuses, but the Professor has been waiting for a long time for her to appear. Laura possesses an extraordinary fighting prowess and is in many ways like Wolverine. She is pursued by sinister figures working for a powerful corporation; this is because her DNA contains the secret that connects her to Logan. A relentless pursuit begins - In this third cinematic outing featuring the Marvel comic book character Wolverine we see the superheroes beset by everyday problems. They are ageing, ailing and struggling to survive financially. A decrepit Logan is forced to ask himself if he can or even wants to put his remaining...            ', '0.0', '8.6', 0, 0, '2017-03-13 15:49:24'),
(110, 'tt1430132', 'http://www.imdb.com/title/tt1430132', 'Wolverine: Imortal', 'The Wolverine', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNzg1MDQxMTQ2OF5BMl5BanBnXkFtZTcwMTk3MjAzOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2013, 'Ação', 'James Mangold', 'Hugh Jackman', 'Tao Okamoto', 'In modern day Japan, Wolverine is out of his depth in an unknown world as he faces his ultimate nemesis in a life-or-death battle that will leave him forever changed. Vulnerable for the first time and pushed to his physical and emotional limits, he confronts not only lethal samurai steel but also his inner struggle against his own immortality, emerging more powerful than we have ever seen him before.               ', '0.0', '6.7', 0, 0, '2017-03-13 15:53:34'),
(111, 'tt0458525', 'http://www.imdb.com/title/tt0458525', 'X-Men Origens: Wolverine', 'X-Men Origins: Wolverine', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZWRhMzdhMzEtZTViNy00YWYyLTgxZmUtMTMwMWM0NTEyMjk3XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX182_CR0,0,182,268_AL_.jpg', 2009, 'Ação', 'Gavin Hood', 'Hugh Jackman', 'Liev Schreiber', 'Two mutant brothers, Logan and Victor, born 200 years ago, suffer childhood trauma and have only each other to depend on. Basically, they\'re fighters and killers, living from war to war through U.S. history. In modern times, a U.S. colonel, Stryker, recruits them and other mutants as commandos. Logan quits and becomes a logger, falling in love with a local teacher. When Logan refuses to rejoin Stryker\'s crew, the colonel sends the murderous Victor. Logan now wants revenge.               ', '0.0', '6.7', 0, 0, '2017-03-13 15:55:27'),
(112, 'tt0376994', 'http://www.imdb.com/title/tt0376994', 'X-Men: O Confronto Final', 'X-Men: The Last Stand', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1NTg2ODA2Nl5BMl5BanBnXkFtZTcwMDc2MjEzMw@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2006, 'Ação', 'Brett Ratner', 'Hugh Jackman', 'Halle Berry', 'When a cure is created, which apparently can turn any mutant into a normal human being, there is outrage amongst the mutant community. Whilst some mutants do like the idea of a cure, including Rogue, many mutants find that there shouldn\'t be a cure. Magneto, who still believes a war is coming, recruits a large team of mutants to take down Warren Worthington II and his cure. Might seem easy for the X-Men to stop, but Magneto has a big advantage, which Wolverine doesn\'t have. Jean Grey has returned, and joined with Magneto. The Phoenix has woken within her, which has the ability to destroy anything in her way, even if that \'anything\' is a X-Men.               ', '0.0', '6.7', 0, 0, '2017-03-13 15:58:33'),
(113, 'tt1877832', 'http://www.imdb.com/title/tt1877832', 'X-Men: Dias de um Futuro Esquecido', 'X-Men: Days of Future Past', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZGIzNWYzN2YtMjcwYS00YjQ3LWI2NjMtOTNiYTUyYjE2MGNkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg', 2014, 'Ação', 'Bryan Singer', 'Hugh Jackman', 'James McAvoy', 'In the future, the mutants and the humans that help them are slaughtered by powerful robots named Sentinels. Professor Xavier, Wolverine, Magneto, Storm, Kitty Pryde and her friends meet at a monastery in China and Xavier explains that the invincible Sentinels were created using the DNA of Mystique that was captured in 1973 when she tried to assassinate their creator Dr. Bolivar Trask. Xavier tells that their only chance is return to 1973 using Pryde\'s ability to join Charles Xavier and Erik Lehnsherr to convince Mystique to give up of her intention. . However, only Wolverine can withstand the damages of the time travel. Will he succeed in stopping Mystique and the Sentinel Program and save the mutants and their human friends from annihilation?               ', '0.0', '8.0', 0, 0, '2017-03-13 16:00:31'),
(114, 'tt0120903', 'http://www.imdb.com/title/tt0120903', 'X-Men: O Filme', 'X-Men', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzU4ODZlYTMtZDg4Yi00OGUzLWEzYjUtZjE2ZmM0NTZkYTQ2XkEyXkFqcGdeQXVyNjExODE1MDc@._V1_UX182_CR0,0,182,268_AL_.jpg', 2000, 'Ação', 'Bryan Singer', 'Hugh Jackman', 'Patrick Stewart', 'In a world where both Mutants and Humans fear each other, Marie, better known as Rogue, runs away from home and hitches a ride with another mutant, known as Logan, a.k.a. Wolverine. Charles Xavier, who owns a school for young mutants, sends Storm and Cyclops to bring them back before it is too late. Magneto, who believes a war is approaching, has an evil plan in mind, and needs young Rogue to help him.               ', '0.0', '7.4', 0, 0, '2017-03-13 16:02:04'),
(115, 'tt1270798', 'http://www.imdb.com/title/tt1270798', 'X-Men: Primeira Classe', 'X: First Class', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTg5OTMxNzk4Nl5BMl5BanBnXkFtZTcwOTk1MjAwNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2011, 'Ação', 'Matthew Vaughn', 'James McAvoy', 'Laurence Belcher', 'Before Charles Xavier and Erik Lensherr took the names Professor X and Magneto, they were two young men discovering their powers for the first time. Before they were archenemies, they were closest of friends, working together, with other Mutants (some familiar, some new), to stop the greatest threat the world has ever known. In the process, a rift between them opened, which began the eternal war between Magneto\'s Brotherhood and Professor X\'s X-MEN.               ', '0.0', '7.8', 0, 0, '2017-03-13 16:04:16'),
(116, 'tt0290334', 'http://www.imdb.com/title/tt0290334', 'X-Men 2', 'X2', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNDk0NjYxMzIzOF5BMl5BanBnXkFtZTYwMTc1MjU3._V1_UX182_CR0,0,182,268_AL_.jpg', 2003, 'Ação', 'Bryan Singer', 'Patrick Stewart', 'Hugh Jackman', 'Several months have passed since The X-Men defeated Magneto and imprisoned him in a seemingly impregnable plastic chamber. One day, a mutant by the name of Nightcrawler infiltrates the White House and attempts to assassinate the president, setting off a chain reaction of anti-mutant measures by the government. Meanwhile, Logan is trying to discover his past. As scientist named William Stryker discovers Professor X\'s secret school and Cerebro, Magneto\'s partner, Mystique, is planning to break her leader out of prison. But when Professor X\'s school is attacked by Stryker\'s forces, Logan, Rogue, Iceman and a few are lucky to escape. Those who remain meet in Boston, where they form an uneasy alliance with Magneto to stop Stryker and rescue Professor X.               ', '0.0', '7.5', 0, 0, '2017-03-13 16:06:08'),
(117, 'tt1371111', 'http://www.imdb.com/title/tt1371111', 'A Viagem', 'Cloud Atlas', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTczMTgxMjc4NF5BMl5BanBnXkFtZTcwNjM5MTA2OA@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2012, 'Drama', 'Tom Tykwer', 'Tom Hanks', 'Halle Berry', 'Everything is connected: an 1849 diary of an ocean voyage across the Pacific; letters from a composer to his lover; a thriller about a conspiracy at a nuclear power plant; a farce about a publisher in a nursing home; a rebellious clone in futuristic Korea; and the tale of a tribe living on post-apocalyptic Hawaii far in the future.               ', '0.0', '7.5', 0, 0, '2017-03-13 16:08:55');
INSERT INTO `movie` (`mov_id`, `mov_id_imdb`, `mov_url_imdb`, `mov_title`, `mov_original_title`, `mov_url_poster`, `mov_year`, `mov_category`, `mov_director`, `mov_starring1`, `mov_starring2`, `mov_sinopsys`, `mov_my_rating`, `mov_imdb_rating`, `mov_netflix`, `mov_watched`, `mov_registered`) VALUES
(118, 'tt0485947', 'http://www.imdb.com/title/tt0485947', 'Sr. Ninguém', 'Mr. Nobody', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTg4ODkzMDQ3Nl5BMl5BanBnXkFtZTgwNTEwMTkxMDE@._V1_UX182_CR0,0,182,268_AL_.jpg', 2009, 'Drama', 'Jaco Van Dormael', 'Jared Leto', 'Sarah Polley', 'In the year 2092, one hundred eighteen year old Nemo is recounting his life story to a reporter. He is less than clear, often times thinking that he is only thirty-four years of age. But his story becomes more confusing after he does focus on the fact of his current real age. He tells of his life at three primary points in his life: at age nine (when his parents divorced), age sixteen and age thirty-four. The confusing aspect of the story is that he tells of alternate life paths, often changing course with the flick of a decision at each of those ages. One life path has him ultimately married to Elise, a depressed woman who never got over the unrequited love she had for a guy named Stefano when she was a teenager and who asked Nemo to swear that when she died he would sprinkle her ashes on Mars. A second life path has him married to Jean. Their life is one of luxury but one also of utter boredom. And a third life path has him in a torrid romance with his step-sister Anna, the two who,...               ', '0.0', '7.9', 0, 0, '2017-03-13 16:11:05'),
(119, 'tt0945513', 'http://www.imdb.com/title/tt0945513', 'Contra o Tempo', 'Source Code', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTY0MTc3MzMzNV5BMl5BanBnXkFtZTcwNDE4MjE0NA@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2011, 'Mistério', 'Duncan Jones', 'Jake Gyllenhaal', 'Michelle Monaghan', 'Army Captain Colter Stevens finds himself working on a special program where his consciousness can be inserted into another human being. The only catch is can only be there for 8 minutes at any given time. That morning, a bomb exploded on a commuter train just outside Chicago. He occupies the body of teacher going to work on that train and is confused as to what he is doing or why he is there as his last memory is of flying his helicopter on a combat mission in Afghanistan. Those in charge of the program explain to him that there is a bomb on the train that must locate it. More importantly, he must identify the bomber as another bombing is expected later that day. He is also told however that he cannot change the past and can only gather information. As he develops a liking for his traveling companion Christina, he sets out to test that theory.               ', '0.0', '7.5', 0, 0, '2017-03-13 16:21:53'),
(120, 'tt1276104', 'http://www.imdb.com/title/tt1276104', 'Looper: Assassinos do Futuro', 'Looper', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTg5NTA3NTg4NF5BMl5BanBnXkFtZTcwNTA0NDYzOA@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2012, 'Ação', 'Rian Johnson', 'Joseph Gordon-Levitt', 'Bruce Willis', 'Joe is classified as a \"looper\", a job in which his employers use time travel to send men from the future to be killed into the past, where Joe can properly dispose of their bodies. However, to tie up loose ends and erase the evidence of his ever being a looper, Joe knows that one day his future self will be sent back for him to kill. When this day comes, Joe\'s future self is prepared and escapes, and the two men struggle separately in the past trying to evade capture and attempting to fulfill their own personal agendas.               ', '0.0', '7.4', 0, 1, '2017-03-13 16:22:41'),
(121, 'tt1136608', 'http://www.imdb.com/title/tt1136608', 'Distrito 9', 'District 9', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTM4OTI1OTM5NF5BMl5BanBnXkFtZTcwMzk5MTU1Mg@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2009, 'Ação', 'Neill Blomkamp', 'Sharlto Copley', 'Jason Cope', 'In 1982, a massive star ship bearing a bedraggled alien population, nicknamed \"The Prawns,\" appeared over Johannesburg, South Africa. Twenty-eight years later, the initial welcome by the human population has faded. The refugee camp where the aliens were located has deteriorated into a militarized ghetto called District 9, where they are confined and exploited in squalor. In 2010, the munitions corporation, Multi-National United, is contracted to forcibly evict the population with operative Wikus van der Merwe in charge. In this operation, Wikus is exposed to a strange alien chemical and must rely on the help of his only two new \'Prawn\' friends.               ', '0.0', '8.0', 0, 0, '2017-03-14 09:28:44'),
(122, 'tt0816711', 'http://www.imdb.com/title/tt0816711', 'Guerra Mundial Z', 'World War Z', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0NTgxMjIxOF5BMl5BanBnXkFtZTcwMDM0MDY1OQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2013, 'Ação', 'Marc Forster', 'Brad Pitt', 'Mireille Enos', 'Life for former United Nations investigator Gerry Lane and his family seems content. Suddenly, the world is plagued by a mysterious infection turning whole human populations into rampaging mindless zombies. After barely escaping the chaos, Lane is persuaded to go on a mission to investigate this disease. What follows is a perilous trek around the world where Lane must brave horrific dangers and long odds to find answers before human civilization falls.               ', '0.0', '7.0', 0, 0, '2017-03-14 09:29:44'),
(123, 'tt0480249', 'http://www.imdb.com/title/tt0480249', 'Eu Sou a Lenda', 'I Am Legend', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYTE1ZTBlYzgtNmMyNS00ZTQ2LWE4NjEtZjUxNDJkNTg2MzlhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg', 2007, 'Drama', 'Francis Lawrence', 'Will Smith', 'Alice Braga', 'Robert Neville is a scientist who was unable to stop the spread of the terrible virus that was incurable and man-made. Immune, Neville is now the last human survivor in what is left of New York City and perhaps the world. For three years, Neville has faithfully sent out daily radio messages, desperate to find any other survivors who might be out there. But he is not alone. Mutant victims of the plague -- The Infected -- lurk in the shadows... watching Neville\'s every move... waiting for him to make a fatal mistake. Perhaps mankind\'s last, best hope, Neville is driven by only one remaining mission: to find a way to reverse the effects of the virus using his own immune blood. But he knows he is outnumbered... and quickly running out of time.               ', '6.0', '7.2', 0, 0, '2017-03-14 09:41:53'),
(124, 'tt0448157', 'http://www.imdb.com/title/tt0448157', 'Hancock', 'Hancock', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTgyMzc4ODU3NV5BMl5BanBnXkFtZTcwNjk5Mzc1MQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2008, 'Ação', 'Peter Berg', 'Will Smith', 'Charlize Theron', 'The powerful superhero John Hancock has become a joke because of his alcoholism and clumsiness. He has also become the most hated man in Los Angeles. Though he has saved many lives, he also destroyed a lot of property, costing the city millions every time he goes into action. When he saves the life of PR expert Ray Embrey from an oncoming train, the executive is thankful and believes he can restore Hancock\'s image as a true superhero. He brings the anti-hero home for dinner and introduces him to his son Aaron, a big fan, and to his wife, Mary. But for some mysterious reason Mary doesn\'t want Hancock anywhere near her or her family.               ', '0.0', '6.4', 0, 0, '2017-03-14 09:49:07'),
(125, 'tt0343818', 'http://www.imdb.com/title/tt0343818', 'Eu, Robô', 'I, Robot', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTQwNzI5NTQ0OF5BMl5BanBnXkFtZTYwMTI3Mjk2._V1_UX182_CR0,0,182,268_AL_.jpg', 2004, 'Ação', 'Alex Proyas', 'Will Smith', 'Bridget Moynahan', ' In 2035, technophobic homicide detective Del Spooner of the Chicago PD heads the investigation of the apparent suicide of leading robotics scientist, Dr. Alfred Lanning. Unconvinced of the motive, Spooner\'s investigation into Lanning\'s death reveals a trail of secrets and agendas within the USR (United States Robotics) corporation and suspicions of murder. Little does he know that his investigation would lead to uncovering a larger threat to humanity.            ', '0.0', '7.1', 0, 0, '2017-03-14 09:56:15'),
(126, 'tt0119654', 'http://www.imdb.com/title/tt0119654', 'MIB: Homens de Preto', 'Men in Black', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNzA2MzI5Nzc0N15BMl5BanBnXkFtZTcwODE2NDU2MQ@@._V1_UY268_CR0,0,182,268_AL_.jpg', 1997, 'Aventura', 'Barry Sonnenfeld', 'Tommy Lee Jones', 'Will Smith', 'Based off of the comic book. Unbeknownst to other people, there is a private agency code named MiB. This agency is some kind of extra terrestrial surveillance corporation. Then, one of the agency\'s finest men only going by the name \"K\" (Tommy Lee Jones) , is recruiting for a new addition to the agency. He has chosen James Edwards (Will Smith) of the N.Y.P.D. Then, one day, a flying saucer crashes into Earth. This was an alien a part of the \"Bug\" race. He takes the body of a farmer (Vincent D\'Onofrio) and heads to New York. He is searching for a super energy source called \"The Galaxy\". Now, Agents J and K must stop the bug before it can escape with the galaxy.               ', '5.0', '7.3', 0, 1, '2017-03-14 09:57:02');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `movie`
--
ALTER TABLE `movie`
  ADD PRIMARY KEY (`mov_id`),
  ADD UNIQUE KEY `mov_id_imdb` (`mov_id_imdb`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `movie`
--
ALTER TABLE `movie`
  MODIFY `mov_id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=127;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
